name: Michiya Abe
description: >
    Master student at UTokyo/NII. I am interested in computer vision and deep learning.
about: >
    Master student at UTokyo/NII. I am interested in computer vision and deep learning.


master_repo: false
url: "https://abemii.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Michiya Abe
  avatar:         "https://pbs.twimg.com/profile_images/1056126288631554049/nDFnhDYK_400x400.jpg"
  email:
  # Social networking links used in footer. Update and remove as you like.
  twitter: Abemii_
  github: https://github.com/Abemii
  stackexchange:
  linkedin: https://www.linkedin.com/in/michiya-abe
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
